server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/pass_local?zeroDateTimeBehavior=convertToNull&characterEncoding=UTF-8&serverTimeZone=Asia/Seoul
    username: pass_local_user
    password: passlocal123
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 20

  batch:
    jdbc:
      # Batch에 사용되는 SQL 초기화 스크립트를 실행함
      # always 설정을 하면 임베디드 타입처럼 항상 활성화시킬 수 있음
      # 초기 수행 이후에는 꺼두어도 됨
      initialize-schema: always
    job:
      # 기본값 true는 Spring Boot 실행 시 등록되어 있는 Job들이 실행됨
      enabled: false
